server:
  port: 8886
spring:
  profiles:
    active: '@activatedProfile@'
  application:
    name: service-essay
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/HealthyPlatform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Gjm9478402?
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      #适配knife4j swagger2 在springboot2.6.x以后修改了请求策略
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heathy.dto
knife4j:
  enable: true